In [4]:
import pandas as pd
from datetime import datetime, timedelta

In [2]:
df = pd.read_csv("test.csv", header = 0)

In [3]:
df.head()

,Date,Task,Category,Start Time,End Time,Alloted Time,Ellapsed Time,Time Difference,Description
0,4/05/2020,Test,Misc,46:43.9,47:50.6,01:06.7,00:01:06.7,0:00:00,Testing the workability of my new system
1,4/05/2020,Electricity Show Demonstration Hunting,Show Development,00:29.3,27:22.4,26:53.1,26:53.1,0:00:00,Why is it so
2,4/05/2020,Test 2,Misc,16:39,16:40,0:01:00,01:07.2,00:07.2,Testing another version of the system
3,4/05/2020,Standardising Teacher Resources,Teacher Resource Development,16:42,17:09,0:20:00,26:27.1,06:27.1,Updating symbols etc
4,4/05/2020,Get over it,Teacher Resource Development,17:14,17:23,0:20:00,09:42.2,"-1 day, 23:49:42.246996",Update with new format and additional resources

In [39]:
def convert(t):
    t_convert = None
    try: 
        ix = t.index('.')
        t = t[:ix]
    except Exception as e:
        print(e)
    
    try:
        t_convert = datetime.strptime(t, "%H:%M:%S")
    except Exception as e:
        print(f"{e}, treating it as a %M:%S situation")
        t_convert = datetime.strptime(t,"%M:%S")
        
    if t_convert != None:
        return round(t_convert.hour*60 + t_convert.minute + t_convert.second/60,1)
    else:
        return "NA"

In [40]:
convert("26:53.1")

time data '26:53' does not match format '%H:%M:%S', treating it as a %M:%S situation

26.9

In [41]:
df["Alloted Time"] = df.apply(lambda row: convert(row["Alloted Time"]),axis = 1)

time data '01:06' does not match format '%H:%M:%S', treating it as a %M:%S situation
time data '26:53' does not match format '%H:%M:%S', treating it as a %M:%S situation
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
time data '0' does not match format '%H:%M:%S', treating it as a %M:%S situation

ValueError: time data '0' does not match format '%M:%S'

In [42]:
df

,Date,Task,Category,Start Time,End Time,Alloted Time,Ellapsed Time,Time Difference,Description
0,4/05/2020,Test,Misc,46:43.9,47:50.6,01:06.7,00:01:06.7,0:00:00,Testing the workability of my new system
1,4/05/2020,Electricity Show Demonstration Hunting,Show Development,00:29.3,27:22.4,26:53.1,26:53.1,0:00:00,Why is it so
2,4/05/2020,Test 2,Misc,16:39,16:40,0:01:00,01:07.2,00:07.2,Testing another version of the system
3,4/05/2020,Standardising Teacher Resources,Teacher Resource Development,16:42,17:09,0:20:00,26:27.1,06:27.1,Updating symbols etc
4,4/05/2020,Get over it,Teacher Resource Development,17:14,17:23,0:20:00,09:42.2,"-1 day, 23:49:42.246996",Update with new format and additional resources
...,...,...,...,...,...,...,...,...,...
126,2020/06/01,Improving time tracking software,Misc,15:30,13:50,20.0,1340.0,NaN,Minor improvements to day view
127,2020/06/01,Troubleshooting,Activity Development,16:00,16:30,30.0,30.0,NaN,Tried with new bolts
128,2020/06/02,Fraedom Coding,Misc,08:40,08:50,10.0,10.0,NaN,CORE Electronics order
129,2020/06/02,Fixing time tracking software,Misc,08:50,09:00,10.0,10.0,NaN,Added toggle for today's sessions
130,2020/06/02,Improving software,Misc,09:01,09:02,1.0,0.33,-0.65,Trying to fix the appending empty lines issue